import test from 'node:test';import assert from 'node:assert/strict';
import {DEFAULT_RECOMMENDATION_CONFIG,decodeRecommendationCursor,encodeRecommendationCursor,rankCandidates,recommendationConfig,type RecommendationCandidate} from '../server/recommendation.js';
const now=new Date('2026-08-22T00:00:00Z');
const candidate=(id:number,userId:number,category='教材',extra:Partial<RecommendationCandidate>={}):RecommendationCandidate=>({id,userId,schoolId:'ruc',campusId:'suzhou',status:'在售',category,price:20,createdAt:now,impressions:0,clicks:0,favorites:0,conversations:0,recentlyExposed:false,...extra});
test('hard filters school, campus and status, but keeps own items',()=>{const rows=rankCandidates([candidate(1,1),candidate(2,2,'教材',{schoolId:'other'}),candidate(3,3,'教材',{status:'已售出'}),candidate(4,4),candidate(5,5,'教材',{campusId:'other'})],{categoryAffinity:{},preferredPrice:null},DEFAULT_RECOMMENDATION_CONFIG,{schoolId:'ruc',campusId:'suzhou',userId:1,seed:'a',now});assert.deepEqual(rows.map(r=>r.candidate.id).sort((a,b)=>a-b),[1,4])});
test('ranking is deterministic, explainable and keeps every eligible item',()=>{const rows=[candidate(1,1),candidate(2,1),candidate(3,1),candidate(4,2),candidate(5,3,'电子产品')];const a=rankCandidates(rows,{categoryAffinity:{教材:1},preferredPrice:20},DEFAULT_RECOMMENDATION_CONFIG,{schoolId:'ruc',campusId:'suzhou',seed:'same',now});const b=rankCandidates(rows,{categoryAffinity:{教材:1},preferredPrice:20},DEFAULT_RECOMMENDATION_CONFIG,{schoolId:'ruc',campusId:'suzhou',seed:'same',now});assert.deepEqual(a,b);assert.equal(a.length,5);assert.ok(a.every(row=>row.reasons.length&&Number.isFinite(row.score.total)));for(let i=2;i<a.length;i++)assert.equal(a[i-2].candidate.userId===a[i-1].candidate.userId&&a[i-1].candidate.userId===a[i].candidate.userId,false)});
test('category window diversity is enforced when alternatives exist',()=>{const rows=[...Array.from({length:6},(_,i)=>candidate(i+1,i+2,'教材')),...Array.from({length:4},(_,i)=>candidate(i+20,i+20,'电子产品'))];const ranked=rankCandidates(rows,{categoryAffinity:{教材:1},preferredPrice:null},DEFAULT_RECOMMENDATION_CONFIG,{schoolId:'ruc',campusId:'suzhou',seed:'category',now});assert.equal(ranked.length,10);for(let i=0;i<=ranked.length-6;i++)assert.ok(ranked.slice(i,i+6).filter(row=>row.candidate.category==='教材').length<=3)});
test('invalid environment weights fall back safely',()=>{const config=recommendationConfig({RECOMMENDATION_WEIGHT_INTEREST:'NaN',RECOMMENDATION_REPEAT_PENALTY:'-2',RECOMMENDATION_MAX_SELLER_CONSECUTIVE:'999'});assert.equal(config.interestWeight,DEFAULT_RECOMMENDATION_CONFIG.interestWeight);assert.equal(config.repeatPenalty,DEFAULT_RECOMMENDATION_CONFIG.repeatPenalty);assert.equal(config.maxSellerConsecutive,2)});
test('signed cursor rejects tampering, wrong context and expiry',()=>{const secret='0123456789abcdef0123456789abcdef',token=encodeRecommendationCursor({offset:20,seed:'abc',issuedAt:now.getTime(),context:'ruc:anon'},secret);assert.equal(decodeRecommendationCursor(token,secret,'ruc:anon',now.getTime())?.offset,20);assert.equal(decodeRecommendationCursor(`${token}x`,secret,'ruc:anon',now.getTime()),null);assert.equal(decodeRecommendationCursor(token,secret,'other',now.getTime()),null);assert.equal(decodeRecommendationCursor(token,secret,'ruc:anon',now.getTime()+31*60_000),null)});
