import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {Pencil,Plus,RefreshCw,School as SchoolIcon,ShieldCheck,X} from 'lucide-react';
import {api,post} from '../api';
import type {AdminSchool,Campus} from '../types';

type Candidate={id:number;email:string;nickname:string;role:string};
export default function AdminSchools(){
  const [schools,setSchools]=useState<AdminSchool[]>([]),[isSuper,setIsSuper]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editor,setEditor]=useState<AdminSchool|'new'|null>(null),[managerTarget,setManagerTarget]=useState<{school:AdminSchool;campus:Campus}|null>(null);
  const load=useCallback(()=>{setLoading(true);setError('');api<{schools:AdminSchool[];isSuperAdmin:boolean}>('/api/admin/schools').then(d=>{setSchools(d.schools);setIsSuper(d.isSuperAdmin)}).catch(e=>setError(e instanceof Error?e.message:'加载失败')).finally(()=>setLoading(false))},[]);useEffect(load,[load]);
  return <div className="admin-page"><div className="admin-page-title admin-title-row"><div><span className="eyebrow">SCHOOLS</span><h1>学校与校区</h1><p>{isSuper?'管理全平台学校、认证邮箱域名、校区和负责人。':'仅查看你负责的校区。'}</p></div>{isSuper&&<button className="button primary" onClick={()=>setEditor('new')}><Plus/>新增学校</button>}</div><div className="admin-toolbar"><button className="admin-refresh" onClick={load}><RefreshCw/>刷新</button></div>{error&&<div className="form-error">{error}</div>}{loading?<div className="admin-table-empty">加载中…</div>:<div className="admin-school-grid">{schools.map(s=><article className="admin-school-card" key={s.id}><div className="admin-school-head"><SchoolIcon/><span><b>{s.name}</b><small>ID：{s.id}</small></span>{isSuper&&<button className="admin-icon-btn" onClick={()=>setEditor(s)}><Pencil/></button>}</div><dl><div><dt>认证邮箱域名</dt><dd>{s.emailDomains.map(d=><code key={d}>@{d}</code>)}</dd></div><div><dt>校区与负责人</dt><dd>{s.campuses.map(c=><div key={c.id}><span className="admin-pill ok">{c.name}（{c.id}）</span>{c.manager?<small>{c.manager.nickname} · {c.manager.email}</small>:<small className="admin-muted">尚未指定</small>}{isSuper&&<button className="button secondary compact" onClick={()=>setManagerTarget({school:s,campus:c})}><ShieldCheck/>指定负责人</button>}</div>)}</dd></div></dl></article>)}</div>}{editor&&<SchoolEditor school={editor==='new'?undefined:editor} onClose={()=>setEditor(null)} onSaved={()=>{setEditor(null);load()}} onError={setError}/>} {managerTarget&&<ManagerEditor school={managerTarget.school} campus={managerTarget.campus} onClose={()=>setManagerTarget(null)} onSaved={()=>{setManagerTarget(null);load()}} onError={setError}/>}</div>;
}

function SchoolEditor({school,onClose,onSaved,onError}:{school?:AdminSchool;onClose:()=>void;onSaved:()=>void;onError:(m:string)=>void}){
  const [id,setId]=useState(school?.id||''),[name,setName]=useState(school?.name||''),[domains,setDomains]=useState((school?.emailDomains||[]).join('\n')),[campuses,setCampuses]=useState((school?.campuses||[]).map(c=>`${c.id}|${c.name}`).join('\n')),[busy,setBusy]=useState(false);
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);const body={id,name,emailDomains:domains.split(/[,\n]/).map(v=>v.trim().replace(/^@/,'')).filter(Boolean),campuses:campuses.split('\n').map(line=>{const [campusId,...rest]=line.split('|');return{id:campusId?.trim(),name:rest.join('|').trim()}}).filter(c=>c.id&&c.name)};try{school?await api(`/api/admin/schools/${school.id}`,{method:'PATCH',body:JSON.stringify(body)}):await post('/api/admin/schools',body);onSaved()}catch(e){onError(e instanceof Error?e.message:'保存失败')}finally{setBusy(false)}};
  return <div className="report-backdrop" onClick={onClose}><form className="report-modal" onSubmit={submit} onClick={e=>e.stopPropagation()}><div className="report-head"><div><b>{school?'编辑学校':'新增学校'}</b><small>学校 ID 创建后不可修改；邮箱域名按完整域名精确核验。</small></div><button type="button" onClick={onClose}><X/></button></div><div className="admin-form-grid"><label>学校 ID<input value={id} onChange={e=>setId(e.target.value.toLowerCase())} readOnly={Boolean(school)} required pattern="[a-z0-9][a-z0-9_-]{0,39}" placeholder="例如 pku"/></label><label>学校名称<input value={name} onChange={e=>setName(e.target.value)} required maxLength={120}/></label><label>认证邮箱域名（每行一个）<textarea value={domains} onChange={e=>setDomains(e.target.value)} required placeholder="example.edu.cn"/></label><label>校区（每行：ID|名称）<textarea value={campuses} onChange={e=>setCampuses(e.target.value)} required placeholder={'main|主校区\nnew|新校区'}/></label></div><div className="report-actions"><button type="button" className="button secondary" onClick={onClose}>取消</button><button className="button primary" disabled={busy}>{busy?'保存中…':'保存'}</button></div></form></div>;
}

function ManagerEditor({school,campus,onClose,onSaved,onError}:{school:AdminSchool;campus:Campus;onClose:()=>void;onSaved:()=>void;onError:(m:string)=>void}){
  const current=school.campuses.find(c=>c.id===campus.id)?.manager;const [users,setUsers]=useState<Candidate[]>([]),[userId,setUserId]=useState(String(current?.id||'')),[busy,setBusy]=useState(false);useEffect(()=>{api<{users:Candidate[]}>(`/api/admin/schools/${school.id}/candidates`).then(d=>setUsers(d.users)).catch(e=>onError(e instanceof Error?e.message:'候选用户加载失败'))},[school.id]);
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{await api(`/api/admin/schools/${school.id}/campuses/${campus.id}/manager`,{method:'PUT',body:JSON.stringify({userId:Number(userId)})});onSaved()}catch(e){onError(e instanceof Error?e.message:'负责人设置失败')}finally{setBusy(false)}};
  return <div className="report-backdrop" onClick={onClose}><form className="report-modal" onSubmit={submit} onClick={e=>e.stopPropagation()}><div className="report-head"><div><b>指定 {school.name} · {campus.name} 负责人</b><small>负责人将获得 admin 权限，但只能查看和管理被分配的校区。</small></div><button type="button" onClick={onClose}><X/></button></div><label>负责人<select value={userId} onChange={e=>setUserId(e.target.value)} required><option value="">请选择平台已有用户</option>{users.map(u=><option value={u.id} key={u.id}>{u.nickname} · {u.email}</option>)}</select></label><div className="report-actions"><button type="button" className="button secondary" onClick={onClose}>取消</button><button className="button primary" disabled={busy||!userId}>{busy?'设置中…':'确认指定'}</button></div></form></div>;
}
