import {useCallback,useEffect,useState} from 'react';
import {ExternalLink,RefreshCw} from 'lucide-react';
import {api} from '../api';
import {formatTimestamp} from '../time';
import type {AdminContext,ScopeApplication} from '../types';

export default function AdminApplications(){
  const [applications,setApplications]=useState<ScopeApplication[]>([]),[context,setContext]=useState<AdminContext|null>(null),[status,setStatus]=useState('待审核'),[schoolId,setSchoolId]=useState(''),[campusId,setCampusId]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  const school=context?.schools.find(s=>s.id===schoolId);
  const load=useCallback(()=>{setLoading(true);const q=new URLSearchParams();if(status)q.set('status',status);if(context?.isSuperAdmin&&schoolId)q.set('schoolId',schoolId);if(context?.isSuperAdmin&&campusId)q.set('campusId',campusId);api<{applications:ScopeApplication[]}>(`/api/admin/scope-applications?${q}`).then(d=>setApplications(d.applications)).catch(e=>setError(e instanceof Error?e.message:'加载失败')).finally(()=>setLoading(false))},[status,schoolId,campusId,context?.isSuperAdmin]);
  useEffect(()=>{api<AdminContext>('/api/admin/context').then(setContext)},[]);useEffect(load,[load]);
  const review=async(a:ScopeApplication,next:'已通过'|'已驳回')=>{const reviewNote=window.prompt(next==='已通过'?'审核备注（可选）':'请填写驳回原因')||'';if(next==='已驳回'&&!reviewNote)return;try{await api(`/api/admin/scope-applications/${a.id}`,{method:'PATCH',body:JSON.stringify({status:next,reviewNote})});load()}catch(e){setError(e instanceof Error?e.message:'审核失败')}};
  return <div className="admin-page"><div className="admin-page-title"><span className="eyebrow">CAMPUS APPLICATIONS</span><h1>学校与校区申请</h1><p>{context?.isSuperAdmin?'查看所有学校和校区，可按范围筛选。':'这里只显示你负责校区的申请。'}</p></div><div className="admin-toolbar"><div className="admin-filters">{['待审核','已通过','已驳回',''].map(v=><button key={v||'all'} className={status===v?'active':''} onClick={()=>setStatus(v)}>{v||'全部'}</button>)}</div>{context?.isSuperAdmin&&<><select value={schoolId} onChange={e=>{setSchoolId(e.target.value);setCampusId('')}}><option value="">全部学校</option>{context.schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={campusId} onChange={e=>setCampusId(e.target.value)}><option value="">全部校区</option>{school?.campuses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></>}<button className="admin-refresh" onClick={load}><RefreshCw/>刷新</button></div>{error&&<div className="form-error">{error}</div>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>申请人</th><th>目标学校 / 校区</th><th>材料</th><th>说明</th><th>状态</th><th>提交时间</th><th>操作</th></tr></thead><tbody>{loading?<tr><td colSpan={7}>加载中…</td></tr>:applications.map(a=><tr key={a.id}><td><b>{a.nickname}</b><br/><small>{a.email}</small></td><td>{a.schoolName}<br/><small>{a.campusName}</small></td><td><a className="admin-icon-btn" href={`/api/admin/scope-applications/${a.id}/evidence`} target="_blank" rel="noreferrer"><ExternalLink/>{a.evidenceName}</a></td><td>{a.note||'—'}{a.reviewNote&&<small>审核：{a.reviewNote}</small>}</td><td><span className="admin-pill">{a.status}</span></td><td>{formatTimestamp(a.createdAt)}</td><td>{a.status==='待审核'&&<div className="admin-row-actions"><button className="button primary compact" onClick={()=>void review(a,'已通过')}>通过</button><button className="button secondary compact" onClick={()=>void review(a,'已驳回')}>驳回</button></div>}</td></tr>)}</tbody></table></div></div>;
}
