import {type NextFunction,type Response,Router} from 'express';
import {hashPassword,type AuthedRequest} from './auth.js';
import {all,generateUsername,mapItem,one,pool,refreshSchoolCatalog,run,type DbRow} from './db.js';
import {cleanText,easterEggs,kinds,normalizeEmail,statuses,validEmail} from './security.js';
import {behaviorMetrics} from './events-store.js';
import {campusBelongsToSchool,campusScopeNames,defaultCampusScope,schoolForEmail} from './campus-catalog.js';
import {canSetManualVerification,isSuperAdminEmail,SUPER_ADMIN_EMAIL} from './admin-permissions.js';
import {canAccessCampus,campusSql,loadAdminScope,type AdminScope} from './admin-scope.js';
import {parseCurrency,validAmount} from './currency.js';
import {getRewardSettings,parseRewardSettings,saveRewardSettings} from './settings.js';
import {grantCurrency} from './wallet.js';

export const adminRouter=Router();
export const REPORT_REASONS=['虚假信息','违规内容','诈骗风险','重复发布','其他'] as const;
const PAGE=20,ID=/^[a-z0-9][a-z0-9_-]{0,39}$/,DOMAIN=/^[a-z0-9.-]+\.[a-z]{2,}$/i;
const adminItemSelect=`SELECT i.*,u.id AS seller_id,u.nickname AS seller_nickname,u.avatar_url AS seller_avatar,u.email AS seller_email,u.email_verified AS seller_email_verified,u.admin_verified AS seller_admin_verified FROM items i JOIN users u ON u.id=i.user_id`;

export function requireAdmin(req:AuthedRequest,res:Response,next:NextFunction){if(!req.user)return res.status(401).json({error:'请先登录后继续'});if(req.user.role!=='admin'&&!isSuperAdminEmail(req.user.email))return res.status(403).json({error:'需要管理员权限'});next()}
type AdminContext=AdminScope&{schoolIds:string[]};
async function adminContext(req:AuthedRequest):Promise<AdminContext>{const scope=await loadAdminScope(req.user!);return{...scope,schoolIds:[...new Set(scope.isSuperAdmin?(await all('SELECT id FROM schools WHERE active=1')).map(r=>String(r.id)):scope.campuses.map(c=>c.schoolId))]}}
function scopeSql(alias:string,ctx:AdminContext){return campusSql(alias,ctx)}
function requireManaged(ctx:AdminContext,schoolId:unknown,campusId:unknown){return canAccessCampus(ctx,schoolId,campusId)}
function dateIso(value:unknown){const date=value instanceof Date?value:new Date(String(value||''));return Number.isNaN(date.getTime())?'':date.toISOString()}

function mapAdminUser(row:DbRow){const schoolId=String(row.school_id||''),campusId=String(row.campus_id||''),names=campusScopeNames(schoolId,campusId);return{id:Number(row.id),username:String(row.username||''),email:String(row.email||''),nickname:String(row.nickname||''),avatarUrl:String(row.avatar_url||''),role:String(row.role||'user')==='admin'?'admin' as const:'user' as const,verified:Boolean(row.verified),emailVerified:Boolean(row.email_verified),adminVerified:Boolean(row.admin_verified),selfOperated:Boolean(row.self_operated),campusVerified:Boolean(row.admin_verified)||(Boolean(row.email_verified)&&schoolForEmail(row.email)?.id===schoolId),schoolId,campusId,...names,emailMessageNotifications:Boolean(row.email_message_notifications),createdAt:dateIso(row.created_at),lastSeenAt:row.last_seen_at?dateIso(row.last_seen_at):null,itemCount:Number(row.item_count||0),isSchoolManager:Boolean(row.is_school_manager),isCampusManager:Boolean(row.is_campus_manager),isSuperAdmin:isSuperAdminEmail(row.email)}}
async function adminUser(id:number){const row=await one(`SELECT u.*,(SELECT COUNT(*) FROM items i WHERE i.user_id=u.id) item_count,(EXISTS(SELECT 1 FROM school_admins sa WHERE sa.user_id=u.id) OR EXISTS(SELECT 1 FROM campus_admins ca WHERE ca.user_id=u.id)) is_school_manager,EXISTS(SELECT 1 FROM campus_admins ca WHERE ca.user_id=u.id AND ca.school_id=u.school_id AND ca.campus_id=u.campus_id) is_campus_manager FROM users u WHERE u.id=?`,[id]);return row?mapAdminUser(row):null}
function mapReport(row:DbRow){const raw=row.item_images,images=Array.isArray(raw)?raw:JSON.parse(String(raw||'[]')),names=campusScopeNames(row.school_id,row.campus_id);return{id:Number(row.id),reason:String(row.reason||''),detail:String(row.detail||''),status:String(row.status||'待处理'),createdAt:dateIso(row.created_at),handledAt:row.handled_at?dateIso(row.handled_at):null,handlerNickname:row.handler_nickname?String(row.handler_nickname):null,schoolId:String(row.school_id),campusId:String(row.campus_id),...names,item:{id:Number(row.item_id),title:String(row.item_title||''),price:Number(row.item_price||0),image:images[0]||'',status:String(row.item_status||'')},reporter:{id:Number(row.reporter_id),nickname:String(row.reporter_nickname||''),email:String(row.reporter_email||'')}}}

async function schoolDetails(ctx:AdminContext){const filter=ctx.isSuperAdmin?'':`WHERE s.id IN (${ctx.schoolIds.map(()=>'?').join(',')})`,args=ctx.isSuperAdmin?[]:ctx.schoolIds,schools=await all(`SELECT s.* FROM schools s ${filter} ORDER BY s.created_at,s.id`,args),allCampuses=await all('SELECT school_id,id,name,active FROM campuses ORDER BY created_at,id'),campuses=ctx.isSuperAdmin?allCampuses:allCampuses.filter(c=>ctx.campuses.some(scope=>scope.schoolId===String(c.school_id)&&scope.campusId===String(c.id))),domains=await all('SELECT school_id,domain FROM school_email_domains ORDER BY domain'),managers=await all('SELECT ca.school_id,ca.campus_id,u.id,u.email,u.nickname FROM campus_admins ca JOIN users u ON u.id=ca.user_id');return schools.map(s=>({id:String(s.id),name:String(s.name),active:Boolean(s.active),emailDomains:domains.filter(d=>d.school_id===s.id).map(d=>String(d.domain)),campuses:campuses.filter(c=>c.school_id===s.id).map(c=>{const manager=managers.find(m=>m.school_id===s.id&&m.campus_id===c.id);return{id:String(c.id),name:String(c.name),active:Boolean(c.active),manager:manager?{id:Number(manager.id),email:String(manager.email),nickname:String(manager.nickname)}:null}}),manager:null}))}

adminRouter.get('/context',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req);res.json({isSuperAdmin:ctx.isSuperAdmin,superAdminEmail:SUPER_ADMIN_EMAIL,managedSchoolIds:ctx.schoolIds,managedCampuses:ctx.campuses,schools:await schoolDetails(ctx)})});
adminRouter.get('/schools',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req);res.json({schools:await schoolDetails(ctx),isSuperAdmin:ctx.isSuperAdmin})});
adminRouter.post('/schools',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req);if(!ctx.isSuperAdmin)return res.status(403).json({error:'只有平台总管理员可以新增学校'});const id=cleanText(req.body.id,40),name=cleanText(req.body.name,120),campuses=Array.isArray(req.body.campuses)?req.body.campuses:[],domains=Array.isArray(req.body.emailDomains)?req.body.emailDomains.map((v:unknown)=>cleanText(v,160).toLowerCase()):[];if(!ID.test(id)||!name)return res.status(400).json({error:'学校 ID 或名称无效'});if(!campuses.length)return res.status(400).json({error:'至少需要一个校区'});if(!domains.length||domains.some((d:string)=>!DOMAIN.test(d)))return res.status(400).json({error:'至少需要一个有效邮箱域名'});if(await one('SELECT id FROM schools WHERE id=?',[id]))return res.status(409).json({error:'学校 ID 已存在'});const connection=await pool.getConnection();try{await connection.beginTransaction();await connection.execute('INSERT INTO schools (id,name) VALUES (?,?)',[id,name]);for(const value of campuses){const campusId=cleanText(value?.id,40),campusName=cleanText(value?.name,120);if(!ID.test(campusId)||!campusName)throw new Error('校区 ID 或名称无效');await connection.execute('INSERT INTO campuses (school_id,id,name) VALUES (?,?,?)',[id,campusId,campusName])}for(const domain of new Set<string>(domains))await connection.execute('INSERT INTO school_email_domains (domain,school_id) VALUES (?,?)',[domain,id]);await connection.commit()}catch(error){await connection.rollback();return res.status(400).json({error:'学校信息无效，或邮箱域名已被其他学校使用'})}finally{connection.release()}await refreshSchoolCatalog();res.status(201).json({schools:await schoolDetails(await adminContext(req))})});
adminRouter.patch('/schools/:id',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req);if(!ctx.isSuperAdmin)return res.status(403).json({error:'只有平台总管理员可以修改学校'});const id=cleanText(req.params.id,40),existing=await one('SELECT id FROM schools WHERE id=?',[id]);if(!existing)return res.status(404).json({error:'学校不存在'});const name=cleanText(req.body.name,120),domains=Array.isArray(req.body.emailDomains)?req.body.emailDomains.map((v:unknown)=>cleanText(v,160).toLowerCase()):null,campuses=Array.isArray(req.body.campuses)?req.body.campuses:null;if(name)await run('UPDATE schools SET name=? WHERE id=?',[name,id]);if(domains){if(!domains.length||domains.some((d:string)=>!DOMAIN.test(d)))return res.status(400).json({error:'邮箱域名无效'});const connection=await pool.getConnection();try{await connection.beginTransaction();await connection.execute('DELETE FROM school_email_domains WHERE school_id=?',[id]);for(const domain of new Set<string>(domains))await connection.execute('INSERT INTO school_email_domains (domain,school_id) VALUES (?,?)',[domain,id]);await connection.commit()}catch{await connection.rollback();return res.status(409).json({error:'邮箱域名已被其他学校使用'})}finally{connection.release()}}if(campuses)for(const value of campuses){const campusId=cleanText(value?.id,40),campusName=cleanText(value?.name,120);if(!ID.test(campusId)||!campusName)return res.status(400).json({error:'校区 ID 或名称无效'});await run('INSERT INTO campuses (school_id,id,name,active) VALUES (?,?,?,1) ON DUPLICATE KEY UPDATE name=VALUES(name),active=1',[id,campusId,campusName])}await refreshSchoolCatalog();res.json({schools:await schoolDetails(await adminContext(req))})});
adminRouter.get('/schools/:id/candidates',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),schoolId=cleanText(req.params.id,40);if(!ctx.isSuperAdmin)return res.status(403).json({error:'只有平台总管理员可以指定负责人'});const rows=await all('SELECT id,email,nickname,role FROM users WHERE school_id=? ORDER BY nickname,email',[schoolId]);res.json({users:rows.map(r=>({id:Number(r.id),email:String(r.email),nickname:String(r.nickname),role:String(r.role)}))})});
adminRouter.put('/schools/:id/manager',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),schoolId=cleanText(req.params.id,40),userId=Number(req.body.userId);if(!ctx.isSuperAdmin)return res.status(403).json({error:'只有平台总管理员可以指定负责人'});const user=await one('SELECT id,email,school_id FROM users WHERE id=?',[userId]);if(!user||String(user.school_id)!==schoolId)return res.status(400).json({error:'负责人必须是该学校已有用户'});if(isSuperAdminEmail(user.email))return res.status(400).json({error:'平台总管理员无需设为学校负责人'});const connection=await pool.getConnection();try{await connection.beginTransaction();await connection.execute('DELETE FROM school_admins WHERE school_id=?',[schoolId]);await connection.execute('INSERT INTO school_admins (school_id,user_id,assigned_by) VALUES (?,?,?)',[schoolId,userId,req.user!.id]);await connection.execute(`UPDATE users SET role='admin',admin_verified=1 WHERE id=?`,[userId]);await connection.commit()}catch(error){await connection.rollback();throw error}finally{connection.release()}res.json({schools:await schoolDetails(await adminContext(req))})});
adminRouter.put('/schools/:id/campuses/:campusId/manager',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),schoolId=cleanText(req.params.id,40),campusId=cleanText(req.params.campusId,40),userId=Number(req.body.userId);if(!ctx.isSuperAdmin)return res.status(403).json({error:'只有平台总管理员可以指定校区负责人'});if(!campusBelongsToSchool(schoolId,campusId))return res.status(400).json({error:'学校与校区不匹配'});const user=await one('SELECT id,email FROM users WHERE id=?',[userId]);if(!user)return res.status(400).json({error:'负责人用户不存在'});if(isSuperAdminEmail(user.email))return res.status(400).json({error:'平台总管理员无需设为校区负责人'});const connection=await pool.getConnection();try{await connection.beginTransaction();await connection.execute('DELETE FROM campus_admins WHERE school_id=? AND campus_id=?',[schoolId,campusId]);await connection.execute('INSERT INTO campus_admins (school_id,campus_id,user_id,assigned_by) VALUES (?,?,?,?)',[schoolId,campusId,userId,req.user!.id]);await connection.execute(`UPDATE users SET role='admin',admin_verified=1 WHERE id=?`,[userId]);await connection.commit()}catch(error){await connection.rollback();throw error}finally{connection.release()}res.json({schools:await schoolDetails(await adminContext(req))})});

adminRouter.get('/stats',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),us=scopeSql('u',ctx),it=scopeSql('i',ctx),rp=scopeSql('i',ctx),uw=us.clause?`WHERE ${us.clause}`:'',iw=it.clause?`WHERE ${it.clause}`:'',rw=rp.clause?`WHERE ${rp.clause}`:'',users=await one(`SELECT COUNT(*) total FROM users u ${uw}`,us.args),items=await one(`SELECT COUNT(*) total FROM items i ${iw}`,it.args),reports=await one(`SELECT COUNT(*) total,SUM(r.status='待处理') pending FROM reports r JOIN items i ON i.id=r.item_id ${rw}`,rp.args);res.json({users:Number(users?.total||0),items:Number(items?.total||0),reports:Number(reports?.total||0),reportsPending:Number(reports?.pending||0),schools:ctx.schoolIds.length})});
adminRouter.get('/economy',async(req:AuthedRequest,res)=>{
  const ctx=await adminContext(req),us=scopeSql('u',ctx),it=scopeSql('i',ctx);
  const uw=us.clause?`WHERE ${us.clause}`:'',iw=it.clause?`WHERE ${it.clause}`:'';
  const users=await one(`SELECT COUNT(*) total,SUM(created_at>=DATE_SUB(CURRENT_TIMESTAMP,INTERVAL 24 HOUR)) last24h FROM users u ${uw}`,us.args);
  const items=await one(`SELECT COUNT(*) total,SUM(created_at>=DATE_SUB(CURRENT_TIMESTAMP,INTERVAL 24 HOUR)) last24h FROM items i ${iw}`,it.args);
  const orders=await one(`SELECT COUNT(*) total,SUM(status='已完成') done,SUM(CASE WHEN status='已完成' THEN amount ELSE 0 END) doneAmount,SUM(created_at>=DATE_SUB(CURRENT_TIMESTAMP,INTERVAL 24 HOUR)) last24h FROM orders o WHERE o.buyer_id IN (SELECT u.id FROM users u ${uw}) OR o.seller_id IN (SELECT u.id FROM users u ${uw})`,[...us.args,...us.args]);
  const balances=await all(`SELECT w.currency,SUM(w.balance) total FROM wallets w JOIN users u ON u.id=w.user_id ${uw} GROUP BY w.currency`,us.args);
  const dist=async(currency:string)=>{const r=await one(`SELECT SUM(COALESCE(w.balance,0)<=0) zero,SUM(COALESCE(w.balance,0) BETWEEN 1 AND 50) b1_50,SUM(COALESCE(w.balance,0) BETWEEN 51 AND 100) b51_100,SUM(COALESCE(w.balance,0) BETWEEN 101 AND 500) b101_500,SUM(COALESCE(w.balance,0)>500) b500p FROM users u LEFT JOIN wallets w ON w.user_id=u.id AND w.currency=? ${uw}`,[currency,...us.args]);return{zero:Number(r?.zero||0),b1_50:Number(r?.b1_50||0),b51_100:Number(r?.b51_100||0),b101_500:Number(r?.b101_500||0),b500p:Number(r?.b500p||0)}};
  const top=async(currency:string)=>{const rows=await all(`SELECT u.nickname,u.email,u.school_id,u.campus_id,w.balance FROM wallets w JOIN users u ON u.id=w.user_id WHERE w.currency=?${us.clause?` AND ${us.clause}`:''} ORDER BY w.balance DESC LIMIT 10`,[currency,...us.args]);return rows.map(r=>{const names=campusScopeNames(String(r.school_id||''),String(r.campus_id||''));return{nickname:String(r.nickname||''),email:String(r.email||''),campusName:names.campusName,balance:Number(r.balance||0)}})};
  res.json({
    users:{total:Number(users?.total||0),last24h:Number(users?.last24h||0)},
    items:{total:Number(items?.total||0),last24h:Number(items?.last24h||0)},
    orders:{total:Number(orders?.total||0),done:Number(orders?.done||0),doneAmount:Number(orders?.doneAmount||0),last24h:Number(orders?.last24h||0)},
    balances:balances.map(b=>({currency:String(b.currency),total:Number(b.total||0)})),
    distribution:{lungmen:await dist('lungmen'),originium:await dist('originium')},
    topHolders:{lungmen:await top('lungmen'),originium:await top('originium')},
  });
});
adminRouter.get('/analytics/recommendations',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req);if(!ctx.isSuperAdmin)return res.status(403).json({error:'只有平台总管理员可以查看全平台推荐分析'});res.json({days:Math.max(1,Math.min(90,Number(req.query.days)||7)),metrics:await behaviorMetrics(Number(req.query.days)||7)})});

adminRouter.get('/users',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),q=cleanText(req.query.q,40),role=cleanText(req.query.role,10),page=Math.max(1,Number(req.query.page)||1),where:string[]=[],args:unknown[]=[];const schoolFilter=cleanText(req.query.schoolId,40),campusFilter=cleanText(req.query.campusId,40);const scope=scopeSql('u',ctx);if(scope.clause){where.push(scope.clause);args.push(...scope.args)}if(q){where.push('(u.email LIKE ? OR u.nickname LIKE ? OR u.username LIKE ?)');args.push(`%${q}%`,`%${q}%`,`%${q}%`)}if(role==='admin'||role==='user'){where.push('u.role=?');args.push(role)}if(campusFilter&&!schoolFilter)return res.status(400).json({error:'校区筛选需要同时提供学校'});if(schoolFilter){if(campusFilter){if(!canAccessCampus(ctx,schoolFilter,campusFilter))return res.status(403).json({error:'无权查看该校区'});where.push('u.school_id=?');args.push(schoolFilter);where.push('u.campus_id=?');args.push(campusFilter)}else{if(!ctx.isSuperAdmin&&!ctx.schoolIds.includes(schoolFilter))return res.status(403).json({error:'无权查看该学校'});where.push('u.school_id=?');args.push(schoolFilter)}}const filter=where.length?`WHERE ${where.join(' AND ')}`:'',count=await one(`SELECT COUNT(*) total FROM users u ${filter}`,args),rows=await all<DbRow>(`SELECT u.*,(SELECT COUNT(*) FROM items i WHERE i.user_id=u.id) item_count,(EXISTS(SELECT 1 FROM school_admins sa WHERE sa.user_id=u.id) OR EXISTS(SELECT 1 FROM campus_admins ca WHERE ca.user_id=u.id)) is_school_manager,EXISTS(SELECT 1 FROM campus_admins ca WHERE ca.user_id=u.id AND ca.school_id=u.school_id AND ca.campus_id=u.campus_id) is_campus_manager FROM users u ${filter} ORDER BY u.id DESC LIMIT ${PAGE} OFFSET ${(page-1)*PAGE}`,args);res.json({users:rows.map(mapAdminUser),total:Number(count?.total||0),page,pageSize:PAGE})});
adminRouter.post('/users',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),emailRaw=cleanText(req.body.email,160),email=emailRaw?normalizeEmail(emailRaw):'',password=String(req.body.password||''),nickname=cleanText(req.body.nickname,24),adminVerified=Boolean(req.body.adminVerified),selfOperated=ctx.isSuperAdmin&&Boolean(req.body.selfOperated),requestedRole=req.body.role==='admin'?'admin':'user',fallback=defaultCampusScope(),matched=email?schoolForEmail(email):undefined,schoolId=cleanText(req.body.schoolId,40)||(matched?.id||fallback.schoolId),campusId=cleanText(req.body.campusId,40)||fallback.campusId;if(!requireManaged(ctx,schoolId,campusId))return res.status(403).json({error:'不能在未授权学校创建用户'});if(!ctx.isSuperAdmin&&requestedRole==='admin')return res.status(403).json({error:'校区负责人不能创建其他管理员'});if(password.length<8||password.length>72)return res.status(400).json({error:'用户信息无效'});if(!validEmail(email))return res.status(400).json({error:'请输入有效邮箱地址'});if(!campusBelongsToSchool(schoolId,campusId))return res.status(400).json({error:'学校与校区不匹配'});if(email&&await one('SELECT id FROM users WHERE email=?',[email]))return res.status(409).json({error:'该邮箱已存在'});const requestedUsername=cleanText(req.body.username,32);if(requestedUsername&&!/^[0-9]{8}$/.test(requestedUsername))return res.status(400).json({error:'用户编号需为 8 位数字'});if(requestedUsername&&await one('SELECT id FROM users WHERE username=?',[requestedUsername]))return res.status(409).json({error:'该用户编号已存在'});const username=requestedUsername||await generateUsername(),emailVerified=matched?.id===schoolId?1:0,result=await run(`INSERT INTO users (username,email,password_hash,nickname,school_id,campus_id,verified,email_verified,admin_verified,self_operated,role) VALUES (?,?,?,?,?,?,?,?,?,?,?)`,[username,email||null,await hashPassword(password),nickname||username,schoolId,campusId,adminVerified||emailVerified,emailVerified,adminVerified?1:0,selfOperated?1:0,ctx.isSuperAdmin?requestedRole:'user']);res.status(201).json({user:await adminUser(Number(result.insertId))})});
adminRouter.patch('/users/:id',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),id=Number(req.params.id),existing=await one('SELECT * FROM users WHERE id=?',[id]);if(!existing)return res.status(404).json({error:'用户不存在'});if(!requireManaged(ctx,existing.school_id,existing.campus_id))return res.status(403).json({error:'不能管理其他学校用户'});if(isSuperAdminEmail(existing.email)&&!ctx.isSuperAdmin)return res.status(403).json({error:'不能修改平台总管理员'});if(isSuperAdminEmail(existing.email)&&(req.body.role!==undefined||req.body.adminVerified!==undefined||req.body.schoolId!==undefined||req.body.campusId!==undefined))return res.status(403).json({error:'平台总管理员的身份与学校归属不可修改'});const updates:string[]=[],args:unknown[]=[];if(req.body.nickname!==undefined){const value=cleanText(req.body.nickname,24);if(value.length<2)return res.status(400).json({error:'昵称至少需要 2 个字符'});updates.push('nickname=?');args.push(value)}if(req.body.wechatId!==undefined){updates.push('wechat_id=?');args.push(cleanText(req.body.wechatId,40))}if(ctx.isSuperAdmin&&req.body.role!==undefined){updates.push('role=?');args.push(req.body.role==='admin'?'admin':'user')}if(ctx.isSuperAdmin&&req.body.adminVerified!==undefined){updates.push('admin_verified=?');args.push(req.body.adminVerified?1:0)}if(ctx.isSuperAdmin&&req.body.selfOperated!==undefined){updates.push('self_operated=?');args.push(req.body.selfOperated?1:0)}if(req.body.emailMessageNotifications!==undefined){updates.push('email_message_notifications=?');args.push(req.body.emailMessageNotifications?1:0)}if(req.body.schoolId!==undefined||req.body.campusId!==undefined){const schoolId=cleanText(req.body.schoolId,40)||String(existing.school_id),campusId=cleanText(req.body.campusId,40)||String(existing.campus_id);if(!ctx.isSuperAdmin&&schoolId!==String(existing.school_id))return res.status(403).json({error:'学校负责人不能变更用户学校'});if(!requireManaged(ctx,schoolId,campusId)||!campusBelongsToSchool(schoolId,campusId))return res.status(400).json({error:'学校与校区不匹配'});updates.push('school_id=?','campus_id=?');args.push(schoolId,campusId)}if(!updates.length)return res.status(400).json({error:'没有需要更新的内容'});args.push(id);await run(`UPDATE users SET ${updates.join(',')} WHERE id=?`,args);res.json({user:await adminUser(id)})});
adminRouter.delete('/users/:id',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),id=Number(req.params.id),existing=await one('SELECT email,school_id,campus_id FROM users WHERE id=?',[id]);if(!existing)return res.status(404).json({error:'用户不存在'});if(id===req.user!.id||isSuperAdminEmail(existing.email))return res.status(400).json({error:'不能删除自己或平台总管理员'});if(!requireManaged(ctx,existing.school_id,existing.campus_id))return res.status(403).json({error:'不能删除其他学校用户'});await run('DELETE FROM users WHERE id=?',[id]);res.json({ok:true})});

adminRouter.patch('/users/:id/verification',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),id=Number(req.params.id),existing=await one('SELECT id,email,role,school_id,campus_id FROM users WHERE id=?',[id]);if(!existing)return res.status(404).json({error:'用户不存在'});if(!requireManaged(ctx,existing.school_id,existing.campus_id))return res.status(403).json({error:'不能认证其他校区用户'});if(isSuperAdminEmail(existing.email)||!canSetManualVerification(ctx.isSuperAdmin,existing.role))return res.status(403).json({error:'普通管理员只能认证本校区普通用户'});await run('UPDATE users SET admin_verified=? WHERE id=?',[req.body.adminVerified?1:0,id]);res.json({user:await adminUser(id)})});

adminRouter.put('/users/:id/campus-manager',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),id=Number(req.params.id),schoolId=cleanText(req.body.schoolId,40),campusId=cleanText(req.body.campusId,40),enabled=Boolean(req.body.enabled);if(!ctx.isSuperAdmin)return res.status(403).json({error:'只有平台总管理员可以设置校区负责人'});if(!campusBelongsToSchool(schoolId,campusId))return res.status(400).json({error:'学校与校区不匹配'});const user=await one('SELECT id,email FROM users WHERE id=?',[id]);if(!user)return res.status(404).json({error:'用户不存在'});if(isSuperAdminEmail(user.email))return res.status(400).json({error:'平台总管理员无需设为校区负责人'});const connection=await pool.getConnection();try{await connection.beginTransaction();if(enabled){await connection.execute('DELETE FROM campus_admins WHERE school_id=? AND campus_id=?',[schoolId,campusId]);await connection.execute('INSERT INTO campus_admins (school_id,campus_id,user_id,assigned_by) VALUES (?,?,?,?)',[schoolId,campusId,id,req.user!.id]);await connection.execute(`UPDATE users SET school_id=?,campus_id=?,role='admin',admin_verified=1 WHERE id=?`,[schoolId,campusId,id])}else{await connection.execute('DELETE FROM campus_admins WHERE school_id=? AND campus_id=? AND user_id=?',[schoolId,campusId,id]);const [remaining]=await connection.execute<any[]>('SELECT (EXISTS(SELECT 1 FROM campus_admins WHERE user_id=?) OR EXISTS(SELECT 1 FROM school_admins WHERE user_id=?)) managed',[id,id]);if(!remaining[0]?.managed)await connection.execute(`UPDATE users SET role='user' WHERE id=?`,[id])}await connection.commit()}catch(error){await connection.rollback();throw error}finally{connection.release()}res.json({user:await adminUser(id)})});

adminRouter.get('/items',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),q=cleanText(req.query.q,40),status=cleanText(req.query.status,20),page=Math.max(1,Number(req.query.page)||1),where:string[]=[],args:unknown[]=[];const scope=scopeSql('i',ctx);if(scope.clause){where.push(scope.clause);args.push(...scope.args)}if(q){where.push('(i.title LIKE ? OR u.nickname LIKE ?)');args.push(`%${q}%`,`%${q}%`)}if(status&&statuses.includes(status as typeof statuses[number])){where.push('i.status=?');args.push(status)}const filter=where.length?`WHERE ${where.join(' AND ')}`:'',count=await one(`SELECT COUNT(*) total FROM items i JOIN users u ON u.id=i.user_id ${filter}`,args),rows=await all<DbRow>(`${adminItemSelect} ${filter} ORDER BY i.id DESC LIMIT ${PAGE} OFFSET ${(page-1)*PAGE}`,args);res.json({items:rows.map(mapItem),total:Number(count?.total||0),page,pageSize:PAGE})});
adminRouter.patch('/items/:id',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),id=Number(req.params.id),item=await one('SELECT id,school_id,campus_id FROM items WHERE id=?',[id]);if(!item)return res.status(404).json({error:'商品不存在'});if(!requireManaged(ctx,item.school_id,item.campus_id))return res.status(403).json({error:'不能管理其他学校商品'});const updates:string[]=[],args:unknown[]=[];if(req.body.status!==undefined){const status=cleanText(req.body.status,20);if(!statuses.includes(status as typeof statuses[number]))return res.status(400).json({error:'商品状态无效'});updates.push('status=?');args.push(status)}if(req.body.kind!==undefined){const kind=cleanText(req.body.kind,10);if(!(kinds as readonly string[]).includes(kind))return res.status(400).json({error:'商品性质无效'});updates.push('kind=?');args.push(kind)}if(req.body.easterEgg!==undefined){const egg=req.body.easterEgg===null||req.body.easterEgg===''?null:cleanText(req.body.easterEgg,20);if(egg!==null&&!(easterEggs as readonly string[]).includes(egg))return res.status(400).json({error:'彩蛋种类无效'});updates.push('easter_egg=?');args.push(egg)}if(!updates.length)return res.status(400).json({error:'没有需要更新的内容'});args.push(id);await run(`UPDATE items SET ${updates.join(',')} WHERE id=?`,args);res.json({ok:true})});
adminRouter.delete('/items/:id',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),id=Number(req.params.id),item=await one('SELECT id,school_id,campus_id FROM items WHERE id=?',[id]);if(!item)return res.status(404).json({error:'商品不存在'});if(!requireManaged(ctx,item.school_id,item.campus_id))return res.status(403).json({error:'不能删除其他学校商品'});await run('DELETE FROM items WHERE id=?',[id]);res.json({ok:true})});

adminRouter.get('/reports',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),status=cleanText(req.query.status,20),page=Math.max(1,Number(req.query.page)||1),where:string[]=[],args:unknown[]=[];const scope=scopeSql('i',ctx);if(scope.clause){where.push(scope.clause);args.push(...scope.args)}if(status){where.push('r.status=?');args.push(status)}const filter=where.length?`WHERE ${where.join(' AND ')}`:'',count=await one(`SELECT COUNT(*) total FROM reports r JOIN items i ON i.id=r.item_id ${filter}`,args),rows=await all<DbRow>(`SELECT r.*,i.school_id,i.campus_id,i.title item_title,i.price item_price,i.status item_status,i.images item_images,u.nickname reporter_nickname,u.email reporter_email,uu.nickname handler_nickname FROM reports r JOIN items i ON i.id=r.item_id JOIN users u ON u.id=r.reporter_id LEFT JOIN users uu ON uu.id=r.handler_id ${filter} ORDER BY (r.status='待处理') DESC,r.id DESC LIMIT ${PAGE} OFFSET ${(page-1)*PAGE}`,args);res.json({reports:rows.map(mapReport),total:Number(count?.total||0),page,pageSize:PAGE})});
adminRouter.patch('/reports/:id',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),id=Number(req.params.id),status=cleanText(req.body.status,20);if(!['待处理','已处理','已驳回'].includes(status))return res.status(400).json({error:'处理状态无效'});const existing=await one('SELECT r.id,i.school_id,i.campus_id FROM reports r JOIN items i ON i.id=r.item_id WHERE r.id=?',[id]);if(!existing)return res.status(404).json({error:'举报不存在'});if(!requireManaged(ctx,existing.school_id,existing.campus_id))return res.status(403).json({error:'不能处理其他学校举报'});await run(`UPDATE reports SET status=?,handled_at=${status==='待处理'?'NULL':'CURRENT_TIMESTAMP'},handler_id=? WHERE id=?`,[status,status==='待处理'?null:req.user!.id,id]);res.json({ok:true})});

adminRouter.get('/settings/reward',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req);if(!ctx.isSuperAdmin)return res.status(403).json({error:'只有平台总管理员可以查看奖励设置'});res.json({settings:await getRewardSettings()})});
adminRouter.put('/settings/reward',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req);if(!ctx.isSuperAdmin)return res.status(403).json({error:'只有平台总管理员可以修改奖励设置'});const settings=parseRewardSettings(req.body);if(!settings)return res.status(400).json({error:'奖励设置格式无效'});await saveRewardSettings(settings);res.json({settings})});
adminRouter.get('/risk-flags',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req);if(!ctx.isSuperAdmin)return res.status(403).json({error:'只有平台总管理员可以查看风控异常'});const rows=await all(`SELECT rf.*,u.email,u.nickname FROM risk_flags rf JOIN users u ON u.id=rf.user_id ORDER BY rf.reviewed ASC,rf.id DESC LIMIT 100`);res.json({flags:rows.map(r=>({id:Number(r.id),userId:Number(r.user_id),email:String(r.email),nickname:String(r.nickname),kind:String(r.kind),detail:String(r.detail),reviewed:Boolean(r.reviewed),createdAt:dateIso(r.created_at)}))})});
adminRouter.patch('/risk-flags/:id',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req);if(!ctx.isSuperAdmin)return res.status(403).json({error:'只有平台总管理员可以处理风控异常'});await run(`UPDATE risk_flags SET reviewed=? WHERE id=?`,[req.body.reviewed?1:0,Number(req.params.id)]);res.json({ok:true})});
adminRouter.post('/wallet/grant',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),email=normalizeEmail(req.body.email),currency=parseCurrency(req.body.currency),amount=validAmount(req.body.amount),reason=cleanText(req.body.reason,200);if(!email||!currency||amount===null||reason.length<2)return res.status(400).json({error:'请提供有效邮箱、币种、正整数数量和至少 2 个字符的原因'});const user=await one('SELECT id,email,nickname,school_id,campus_id FROM users WHERE email=?',[email]);if(!user)return res.status(404).json({error:'未找到该用户'});if(!requireManaged(ctx,user.school_id,user.campus_id))return res.status(403).json({error:'不能向其他学校用户发放奖励'});const operator=String(req.user!.email||req.user!.nickname||'管理员'),{after}=await grantCurrency({userId:Number(user.id),currency,amount,reason,operator});res.status(201).json({userId:Number(user.id),currency,amount,balanceAfter:after})});
adminRouter.get('/users/:id/wallet',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),id=Number(req.params.id),user=await one('SELECT id,email,nickname,school_id,campus_id FROM users WHERE id=?',[id]);if(!user)return res.status(404).json({error:'用户不存在'});if(!requireManaged(ctx,user.school_id,user.campus_id))return res.status(403).json({error:'不能查看其他学校用户的钱包'});const balances=await all('SELECT currency,balance FROM wallets WHERE user_id=?',[id]),entries=await all('SELECT id,currency,amount,balance_after,reason,operator,created_at FROM currency_ledger WHERE user_id=? ORDER BY id DESC LIMIT 50',[id]);res.json({user:{id:Number(user.id),email:String(user.email),nickname:String(user.nickname)},balances:balances.map(b=>({currency:String(b.currency),balance:Number(b.balance)})),entries:entries.map(e=>({id:Number(e.id),currency:String(e.currency),amount:Number(e.amount),balanceAfter:Number(e.balance_after),reason:String(e.reason),operator:String(e.operator),createdAt:dateIso(e.created_at)}))})});
adminRouter.get('/users/:id/items',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),id=Number(req.params.id),user=await one('SELECT id,school_id,campus_id FROM users WHERE id=?',[id]);if(!user)return res.status(404).json({error:'用户不存在'});if(!requireManaged(ctx,user.school_id,user.campus_id))return res.status(403).json({error:'不能查看其他学校用户'});const rows=await all<DbRow>(`${adminItemSelect} WHERE i.user_id=? ORDER BY i.id DESC LIMIT 200`,[id]);res.json({items:rows.map(mapItem)})});
adminRouter.get('/users/:id/orders',async(req:AuthedRequest,res)=>{const ctx=await adminContext(req),id=Number(req.params.id),user=await one('SELECT id,school_id,campus_id FROM users WHERE id=?',[id]);if(!user)return res.status(404).json({error:'用户不存在'});if(!requireManaged(ctx,user.school_id,user.campus_id))return res.status(403).json({error:'不能查看其他学校用户'});const rows=await all<DbRow>(`SELECT o.*,b.nickname buyer_nickname,s.nickname seller_nickname FROM orders o JOIN users b ON b.id=o.buyer_id JOIN users s ON s.id=o.seller_id WHERE o.buyer_id=? OR o.seller_id=? ORDER BY o.id DESC LIMIT 200`,[id,id]);res.json({orders:rows.map(r=>({id:Number(r.id),itemId:r.item_id?Number(r.item_id):null,itemTitle:String(r.item_title||''),currency:String(r.currency),amount:Number(r.amount),status:String(r.status),role:Number(r.buyer_id)===id?'buyer':'seller',buyer:{nickname:String(r.buyer_nickname||'')},seller:{nickname:String(r.seller_nickname||'')},paidAt:r.paid_at?dateIso(r.paid_at):null,completedAt:r.completed_at?dateIso(r.completed_at):null,createdAt:dateIso(r.created_at)}))})});
