import {createHash,randomUUID} from 'node:crypto';
import {all,mapItem,type DbRow} from './db.js';
import {decodeRecommendationCursor,encodeRecommendationCursor,rankCandidates,recommendationConfig,type RecommendationCandidate} from './recommendation.js';
import {runtimeSecret} from './runtime-secret.js';

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const itemSelect=`SELECT i.*,u.id AS seller_id,u.nickname AS seller_nickname,u.avatar_url AS seller_avatar,u.email AS seller_email,u.email_verified AS seller_email_verified,u.admin_verified AS seller_admin_verified`;
function rolloutBucket(value:string){return createHash('sha256').update(value).digest().readUInt32BE(0)%100}
function secret(){return runtimeSecret('cursor')}
export function recommendationAssignment(identity:string){return process.env.RECOMMENDATION_ENABLED==='true'&&rolloutBucket(identity)<Math.max(0,Math.min(100,Number(process.env.RECOMMENDATION_ROLLOUT_PERCENT)||0));}
export class RecommendationInputError extends Error{}

async function signals(userId:number|undefined,snapshot:Date){
  if(!userId)return{categoryAffinity:{},preferredPrice:null};
  const rows=await all<DbRow>(`SELECT i.category,SUM(CASE e.event_type WHEN 'item_click' THEN 1 WHEN 'favorite_add' THEN 3 WHEN 'conversation_start' THEN 5 ELSE 0 END) strength,SUM(i.price*CASE e.event_type WHEN 'item_click' THEN 1 WHEN 'favorite_add' THEN 3 WHEN 'conversation_start' THEN 5 ELSE 0 END)/NULLIF(SUM(CASE e.event_type WHEN 'item_click' THEN 1 WHEN 'favorite_add' THEN 3 WHEN 'conversation_start' THEN 5 ELSE 0 END),0) preferred_price FROM behavior_events e JOIN items i ON i.id=e.item_id WHERE e.user_id=? AND e.occurred_at>=DATE_SUB(?,INTERVAL 30 DAY) AND e.occurred_at<? AND e.event_type IN ('item_click','favorite_add','conversation_start') GROUP BY i.category`,[userId,snapshot,snapshot]);
  const max=Math.max(1,...rows.map(row=>Number(row.strength))),categoryAffinity=Object.fromEntries(rows.map(row=>[String(row.category),Number(row.strength)/max])),weight=rows.reduce((sum,row)=>sum+Number(row.strength),0),preferredPrice=weight?rows.reduce((sum,row)=>sum+Number(row.preferred_price)*Number(row.strength),0)/weight:null;return{categoryAffinity,preferredPrice};
}

export async function recommendations(input:{schoolId:string;sessionId:string;userId?:number;cursor?:string;pageSize:number}){
  if(!UUID.test(input.sessionId))throw new RecommendationInputError('sessionId 格式无效');const identity=input.userId?`user:${input.userId}`:`session:${input.sessionId}`,personalized=recommendationAssignment(identity),config=recommendationConfig(process.env),version=personalized?config.algorithmVersion:'latest-v1',context=`${input.schoolId}:${identity}:${version}`;
  const decoded=input.cursor?decodeRecommendationCursor(input.cursor,secret(),context):null;if(input.cursor&&!decoded)throw new RecommendationInputError('cursor 无效或已过期');const issuedAt=decoded?.issuedAt??Date.now(),seed=decoded?.seed??randomUUID(),offset=decoded?.offset??0,requestId=randomUUID();
  const snapshot=new Date(issuedAt);
  if(!personalized){const args:unknown[]=[input.schoolId,snapshot],own=input.userId?' AND i.user_id<>?':'';if(input.userId)args.push(input.userId);const rows=await all<DbRow>(`${itemSelect} FROM items i JOIN users u ON u.id=i.user_id WHERE i.school_id=? AND i.status='在售' AND i.created_at<=?${own} ORDER BY i.created_at DESC,i.id DESC LIMIT ${input.pageSize+1} OFFSET ${offset}`,args),hasMore=rows.length>input.pageSize,items=rows.slice(0,input.pageSize).map(mapItem);return{items,requestId,algorithmVersion:version,nextCursor:hasMore?encodeRecommendationCursor({offset:offset+input.pageSize,seed,issuedAt,context},secret()):null,previousCursor:offset>0?encodeRecommendationCursor({offset:Math.max(0,offset-input.pageSize),seed,issuedAt,context},secret()):null,hasMore};}
  const own=input.userId?' AND i.user_id<>?':'';
  const rows=await all<DbRow>(`${itemSelect},COALESCE(m.impressions,0) impressions,COALESCE(m.clicks,0) clicks,COALESCE(m.favorites,0) favorites,COALESCE(m.conversations,0) conversations,MAX(CASE WHEN recent.event_id IS NULL THEN 0 ELSE 1 END) recently_exposed FROM items i JOIN users u ON u.id=i.user_id LEFT JOIN (SELECT item_id,SUM(event_type='item_impression') impressions,SUM(event_type='item_click') clicks,SUM(event_type='favorite_add') favorites,SUM(event_type='conversation_start') conversations FROM behavior_events WHERE occurred_at>=DATE_SUB(?,INTERVAL 30 DAY) AND occurred_at<? GROUP BY item_id) m ON m.item_id=i.id LEFT JOIN behavior_events recent ON recent.item_id=i.id AND recent.session_id=? AND recent.event_type='item_impression' AND recent.occurred_at>=DATE_SUB(?,INTERVAL 24 HOUR) AND recent.occurred_at<? WHERE i.school_id=? AND i.status='在售' AND i.created_at<=?${own} GROUP BY i.id,u.id ORDER BY i.created_at DESC LIMIT 500`,[snapshot,snapshot,input.sessionId,snapshot,snapshot,input.schoolId,snapshot,...(input.userId?[input.userId]:[])]);
  const candidates=rows.map(row=>({id:Number(row.id),userId:Number(row.user_id),schoolId:String(row.school_id),status:String(row.status),category:String(row.category),price:Number(row.price),createdAt:String(row.created_at),impressions:Number(row.impressions),clicks:Number(row.clicks),favorites:Number(row.favorites),conversations:Number(row.conversations),recentlyExposed:Boolean(row.recently_exposed),row})) as Array<RecommendationCandidate&{row:DbRow}>;
  const ranked=rankCandidates(candidates,await signals(input.userId,snapshot),config,{schoolId:input.schoolId,userId:input.userId,seed,now:snapshot}),page=ranked.slice(offset,offset+input.pageSize),hasMore=offset+input.pageSize<ranked.length;
  return{items:page.map(result=>({...mapItem(result.candidate.row),recommendationReasons:result.reasons})),requestId,algorithmVersion:version,nextCursor:hasMore?encodeRecommendationCursor({offset:offset+input.pageSize,seed,issuedAt,context},secret()):null,previousCursor:offset>0?encodeRecommendationCursor({offset:Math.max(0,offset-input.pageSize),seed,issuedAt,context},secret()):null,hasMore};
}
