import {Router} from 'express';
import multer from 'multer';
import {type AuthedRequest,requireAuth} from './auth.js';
import {all,dateIso,one,pool,run,type DbRow} from './db.js';
import {campusBelongsToSchool} from './campus-catalog.js';
import {cleanText} from './security.js';
import {cosConfigured,signedObjectUrl,uploadPrivateEvidence,validImageSignature} from './storage.js';
import {canAccessCampus,campusSql,loadAdminScope} from './admin-scope.js';

export const scopeApplicationRouter=Router(),adminScopeApplicationRouter=Router();
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:8*1024*1024,files:1},fileFilter:(_req,file,cb)=>cb(null,['application/pdf','image/jpeg','image/png','image/webp'].includes(file.mimetype))});
const validEvidence=(file:Express.Multer.File)=>file.mimetype==='application/pdf'?file.buffer.subarray(0,5).toString()==='%PDF-':validImageSignature(file.buffer);
const map=(r:DbRow)=>({id:Number(r.id),userId:Number(r.user_id),nickname:String(r.nickname||''),email:String(r.email||''),requestedSchoolId:String(r.requested_school_id),requestedCampusId:String(r.requested_campus_id),schoolName:String(r.school_name||''),campusName:String(r.campus_name||''),evidenceName:String(r.evidence_name),note:String(r.note||''),status:String(r.status),reviewNote:String(r.review_note||''),reviewerNickname:r.reviewer_nickname?String(r.reviewer_nickname):null,createdAt:dateIso(r.created_at),reviewedAt:r.reviewed_at?dateIso(r.reviewed_at):null});
const select=`SELECT a.*,u.email,u.nickname,s.name school_name,c.name campus_name,rv.nickname reviewer_nickname FROM school_scope_applications a JOIN users u ON u.id=a.user_id JOIN schools s ON s.id=a.requested_school_id JOIN campuses c ON c.school_id=a.requested_school_id AND c.id=a.requested_campus_id LEFT JOIN users rv ON rv.id=a.reviewer_id`;

scopeApplicationRouter.use(requireAuth);
scopeApplicationRouter.get('/',async(req:AuthedRequest,res)=>{const rows=await all<DbRow>(`${select} WHERE a.user_id=? ORDER BY a.id DESC`,[req.user!.id]);res.json({applications:rows.map(map)})});
scopeApplicationRouter.post('/',upload.single('evidence'),async(req:AuthedRequest,res)=>{const schoolId=cleanText(req.body.schoolId,40),campusId=cleanText(req.body.campusId,40),note=cleanText(req.body.note,500),file=req.file;if(!campusBelongsToSchool(schoolId,campusId))return res.status(400).json({error:'请选择有效的学校和校区'});if(!file||!validEvidence(file))return res.status(400).json({error:'请上传有效的 PDF、JPG、PNG 或 WebP 佐证材料'});if(!cosConfigured())return res.status(503).json({error:'材料存储服务暂不可用'});if(await one(`SELECT id FROM school_scope_applications WHERE user_id=? AND status='待审核'`,[req.user!.id]))return res.status(409).json({error:'你已有待审核申请，请等待管理员处理'});const key=await uploadPrivateEvidence(file),result=await run(`INSERT INTO school_scope_applications (user_id,requested_school_id,requested_campus_id,evidence_key,evidence_name,note) VALUES (?,?,?,?,?,?)`,[req.user!.id,schoolId,campusId,key,cleanText(file.originalname,255)||'佐证材料',note]);res.status(201).json({id:Number(result.insertId)})});

adminScopeApplicationRouter.get('/',async(req:AuthedRequest,res)=>{const scope=await loadAdminScope(req.user!),status=cleanText(req.query.status,20),schoolId=cleanText(req.query.schoolId,40),campusId=cleanText(req.query.campusId,40),where:string[]=[],args:unknown[]=[];const scoped=campusSql('a',scope);if(scoped.clause){where.push(scoped.clause.replaceAll('.school_id','.requested_school_id').replaceAll('.campus_id','.requested_campus_id'));args.push(...scoped.args)}if(status){where.push('a.status=?');args.push(status)}if(scope.isSuperAdmin&&schoolId){where.push('a.requested_school_id=?');args.push(schoolId)}if(scope.isSuperAdmin&&campusId){where.push('a.requested_campus_id=?');args.push(campusId)}const rows=await all<DbRow>(`${select}${where.length?` WHERE ${where.join(' AND ')}`:''} ORDER BY (a.status='待审核') DESC,a.id DESC`,args);res.json({applications:rows.map(map),isSuperAdmin:scope.isSuperAdmin,managedCampuses:scope.campuses})});
adminScopeApplicationRouter.get('/:id/evidence',async(req:AuthedRequest,res)=>{const scope=await loadAdminScope(req.user!),row=await one('SELECT requested_school_id,requested_campus_id,evidence_key FROM school_scope_applications WHERE id=?',[Number(req.params.id)]);if(!row)return res.status(404).json({error:'申请不存在'});if(!canAccessCampus(scope,row.requested_school_id,row.requested_campus_id))return res.status(403).json({error:'不能查看其他校区的材料'});res.redirect(await signedObjectUrl(String(row.evidence_key)))});
adminScopeApplicationRouter.patch('/:id',async(req:AuthedRequest,res)=>{const scope=await loadAdminScope(req.user!),id=Number(req.params.id),decision=cleanText(req.body.status,20),reviewNote=cleanText(req.body.reviewNote,500);if(!['已通过','已驳回'].includes(decision))return res.status(400).json({error:'审核结果无效'});const row=await one('SELECT * FROM school_scope_applications WHERE id=?',[id]);if(!row)return res.status(404).json({error:'申请不存在'});if(String(row.status)!=='待审核')return res.status(409).json({error:'该申请已经处理'});if(!canAccessCampus(scope,row.requested_school_id,row.requested_campus_id))return res.status(403).json({error:'不能处理其他校区申请'});const connection=await pool.getConnection();try{await connection.beginTransaction();await connection.execute(`UPDATE school_scope_applications SET status=?,review_note=?,reviewer_id=?,reviewed_at=CURRENT_TIMESTAMP WHERE id=? AND status='待审核'`,[decision,reviewNote,req.user!.id,id]);if(decision==='已通过')await connection.execute('UPDATE users SET school_id=?,campus_id=?,verified=1,admin_verified=1 WHERE id=?',[row.requested_school_id,row.requested_campus_id,row.user_id]);await connection.commit()}catch(error){await connection.rollback();throw error}finally{connection.release()}res.json({ok:true})});
